# Numpy Exercises

## Warm up

Selected from the collection
[100 numpy exercises](https://github.com/rougier/numpy-100/blob/master/100%20Numpy%20exercises%20no%20solution.ipynb)

#### Import NumPy

Import the numpy package under the name np and check the version
<!---
np.__version__
--->

In [1]:
import numpy as np

#### Create a null vector of size 10
<!---
np.zeros()
--->

In [8]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Find indices of non-zero elements from [1,2,0,0,4,0]

<!---
np.nonzero()
--->

In [7]:
arr = np.array([1,2,0,0,4,0])
print(arr[arr>0])

[1 2 4]


#### Create a 3x3 identity matrix

<!---
np.eye()
--->

In [10]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Array creation and manipulation

By using miscellaneous constructors, indexing, slicing, and simple operations (+, −, *, :),
large arrays with various patterns can be created. Find a way to create these arrays.

1. Create the following arrays:

a) 
  
  $$
\begin{pmatrix}
    1. & 1. & 1. & 1. \\
    1. & 1. & 1. & 1. \\
    1. & 1. & 1. & 2. \\
    1. & 6. & 1. & 1. \\
\end{pmatrix}
$$



In [16]:
a = np.ones([4,4])
a[3,1]+=5
a[2,3]+=1
print(a)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 2.]
 [1. 6. 1. 1.]]


  b)
$$
\begin{pmatrix}
    0 & 0 & 0 & 0 & 0 \\
    2 & 0 & 0 & 0 & 0 \\
    0 & 3 & 0 & 0 & 0 \\
    0 & 0 & 4 & 0 & 0 \\
    0 & 0 & 0 & 5 & 0 \\
    0 & 0 & 0 & 0 & 6 \\
\end{pmatrix}
$$

<!---
np.diag(1+np.arange(4),k=-1)
--->

In [65]:
# b = np.zeros([5,5])
eye_arr = np.eye(5)  
add = np.arange(2, 7)
np.fill_diagonal(eye_arr,list(add))
result = np.concatenate(([[0,0,0,0,0]], eye_arr, ), axis=0)
print(result)



[[0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 4. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 6.]]


c) Form this 2-D array (without explicitly typing it):

$$
\begin{pmatrix}
    1 & 6 & 11 \\
    2 & 7 & 12 \\
    3 & 8 & 13 \\
    4 & 9 & 14 \\
    5 & 10 & 15 \\
\end{pmatrix}
$$

In [72]:
arr = np.arange(1,16)
result = arr.reshape((3,5))
print(result.T)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


## A simple calculation

1. Create a two dimensional array `a` with different number of rows and columns
    * Divide the **columns** of `a` with a one dimensional array
    * Divide the **rows** of `a` with a one dimensional array
 
Do you notice some problem? 

What error message do you get?
 
<!---
a = np.random.randint(2,4,(4,3))
b = np.arange(1,4)
c = np.arange(1,5)

Divide columns
np.divide(a, b)

Divide rows
np.divide(a.T, c).T
--->



In [85]:
a = np.random.randint(2,4,(4,3))
b = np.arange(1,4)
c = np.arange(1,5)
# np.divide(a, b)
# np.divide(a.T, c).T

## Sorting and indexing

a) Generate a 10 × 3 array of random numbers ($\in [0, 1[$). 
For each row, get the index of the number closest to 0.5. 
Hint: Use ``abs`` and ``argmin`` to find the column $j$ closest for
each row. 

b) Use advanced indexing to extract the numbers closest to 0.5 for each row. 
Hint: use fancy indexing `arr[i, j]`, 
$i$ must contain the row numbers corresponding to stuff in $j$.

<!--
A = np.random.rand(10, 3) # generate array of random numbers
B = np.abs(A - 0.5) # smallest values are the closest ones to 0.5
idx = np.argmin(B, axis=1) # indices of the values closest 0.5
A[np.arange(len(A)), idx] # use fancy indexing to get the values closest to 0.5
-->



In [103]:
arr = np.random.random((10, 3))
arr_2 = np.abs(arr - 0.5)
print(arr)
indexes = np.argmin(arr_2, axis=1)
arr[np.arange(len(arr)), indexes]

[[0.66959192 0.19554021 0.80236688]
 [0.86441683 0.50887403 0.10952987]
 [0.37172294 0.34156995 0.38024799]
 [0.24699503 0.25489068 0.14898656]
 [0.491183   0.48800841 0.07917749]
 [0.34327695 0.5222818  0.39113564]
 [0.72343083 0.41383217 0.26370002]
 [0.00988828 0.64689994 0.46886896]
 [0.01046837 0.54330901 0.82238276]
 [0.41654608 0.26875734 0.23516398]]


array([0.66959192, 0.50887403, 0.38024799, 0.25489068, 0.491183  ,
       0.5222818 , 0.41383217, 0.46886896, 0.54330901, 0.41654608])

##  Solving Systems of Linear Equations

You find three shopping bags with following content:

* bag A: 10 kg apples, 5 kg pears, 1 kg oranges (35.35 EUR)
* bag B: 1 kg apples, 8 kg pears, 1 kg oranges (24.91 EUR)
* bag C: 9 kg apples, 3 kg pears, 5 kg oranges (40.38 EUR)

Determine the price of apples, oranges and pears:
1. Formulate a linear system of equations describing the shopping bags.
2. Use ``scipy.linalg.solve()`` (or ``numpy.linalg``) to solve the system of equations.
3. Verify the results by using ``np.dot()``.

In [111]:
from scipy import linalg
#  TEST
# a = np.array([[2, 1], [1, 1]])
# b = np.array([6, 5])
# x = linalg.solve(a, b)
# print(x)
a = np.array([[10,5,1], [1,8,1], [9,3,5]])
b = np.array([35.35, 24.91, 40.38])
x = linalg.solve(a,b)
print(x)

[1.99 2.49 3.  ]
